### ISSUE TITLE
speech popup hidden

### ISSUE THREAD

**Issue by lalop** [tiff/wysihtml5#436]
hello,
I've added wysihtml5 on my app but when I click on the speech command nothing  happen.

**Comment by lalop** [comment]
I found the problem in my css :

``` css
input::-webkit-input-speech-button{ -webkit-appearance: none;display: none;  }
```

So I couldn't click on the hidden microphone button
